### ISSUE TITLE
build from source doesn't work on OSX 10.8

### ISSUE THREAD

**Issue by jerryjeremiah** [EUA/wxHexEditor#74]
My system is OSX 10.8.5 and I am using the built in clang with the following version info:

>Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
>Target: x86_64-apple-darwin12.6.0
>Thread model: posix

So I built wxWidgets with the OSX instructions in https://github.com/EUA/wxHexEditor/blob/master/COMPILE amending it to use the correct SDK:

    tar xvf wxWidgets-3.1.0.tar.bz2 
    cd wxWidgets-3.1.0
    mkdir release 
    cd release 
    export arch_flags="-arch i386" 
    ../configure CFLAGS="$arch_flags" CXXFLAGS="$arch_flags" CPPFLAGS="$arch_flags" LDFLAGS="$arch_flags" OBJCFLAGS="$arch_flags" OBJCXXFLAGS="$arch_flags" --with-macosx-version-min=10.6 --with-macosx-sdk=/Volumes/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk/ --enable-monolithic --enable-static --disable-debug --disable-shared --with-regex=builtin --with-expat=builtin --enable-unicode 

It built with no issues.  Then I tried to build wxHexEditor on OSX using the subsequent instuctions amending it with the correct ex-config:

    make mac WXCONFIG=../wxWidgets-3.1.0/release/wx-config OPTFLAGS="-arch i386"

As part of the build clang tries to execute this line:

    c++ -c `../wxWidgets-3.1.0/release/wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -fopenmp -Wall -arch i386   src/HexEditorGui.cpp -o src/HexEditorGui.o

where the `../wxWidgets-3.1.0/release/wx-config --cxxflags` bit returns:

    -I/Users/test/Downloads/wxWidgets-3.1.0/release/lib/wx/include/osx_cocoa-unicode-static-3.1 -I/Users/test/Downloads/wxWidgets-3.1.0/include -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ 

And that's where clang dies with this error message:

    clang: warning: argument unused during compilation: '-fopenmp'
    0  clang 0x0000000100c57bb2 main + 12932498
    Stack dump:
    0.	Program arguments: /usr/bin/clang -cc1 -triple i386-apple-macosx10.8.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name HexEditorGui.cpp -pic-level 2 -mdisable-fp-elim -masm-verbose -target-cpu yonah -target-linker-version 136 -coverage-file /Users/test/Downloads/wxHexEditor-master/src/HexEditorGui.o -resource-dir /usr/bin/../lib/clang/4.2 -dependency-file src/HexEditorGui.d -MT src/HexEditorGui.o -D _FILE_OFFSET_BITS=64 -D wxDEBUG_LEVEL=0 -D __WXMAC__ -D __WXOSX__ -D __WXOSX_COCOA__ -I /Users/test/Downloads/wxWidgets-3.1.0/release/lib/wx/include/osx_cocoa-unicode-static-3.1 -I /Users/test/Downloads/wxWidgets-3.1.0/include -I udis86 -I mhash/include -fmodule-cache-path /var/folders/t4/92w9s61j7yz0nqrnyfmw_vgm0000gn/T/clang-module-cache -Wall -fdeprecated-macro -fdebug-compilation-dir /Users/test/Downloads/wxHexEditor-master -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-fragile-10.8.0 -fobjc-default-synthesize-properties -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o src/HexEditorGui.o -x c++ src/HexEditorGui.cpp 
    1.	/Users/test/Downloads/wxWidgets-3.1.0/include/wx/defs.h:411:10: current parser token 'if'
    clang: error: unable to execute command: Segmentation fault: 11
    clang: error: clang frontend command failed due to signal (use -v to see invocation)
    Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
    Target: i386-apple-darwin12.6.0
    Thread model: posix
    clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
    clang: error: unable to execute command: Segmentation fault: 11
    clang: note: diagnostic msg: Error generating preprocessed source(s).

I don't know what it doesn't like about the line at /Users/test/Downloads/wxWidgets-3.1.0/include/wx/defs.h:411:10
but it shouldn't kill the compiler so that's a problem.

Is there a way to get it to compile?  I don't have the luxury of upgrading xcode because it would require a newer OS and I have tried upgrading to 10.12 three times and it just gets stuck during the first reboot and never installs the new OS...

**Comment by jerryjeremiah** [comment]
Can I just ask, what version of XCode can be used to compile this successfully?

I don't personally have the ability to upgrade XCode without upgrading OSX but I have tried that several times and it just bricks the machine and I have to reinstall the OS from scratch.  But some version of XCode must have been used or there wouldn't be instructions for OSX at all.  

Was it a newer version or an older version of XCode?

**Comment by EUA** [comment]
Hi,
All I know is, I has successfully compile wxWidgets and wxHexEditor on OSX 10.8 somehow.
But unfortunately I don't remember how did I do that. Not using OSX, just tried to setup hackintosh for test wxHexEditor under OSX.
Probably I could used gcc also.
Will update COMPILE file and here at my next boot to OSX.

**Comment by RuneN007** [comment]
# Here is how I compiled it in OS X Sierra.

## Download and compile wxWidgets-3.0.3

```
unzip wxWidgets-3.0.3.zip
cd wxWidgets-3.0.3
mkdir release
cd release
```

You need to have the X-Code for the minimum version of OS X you will support.

```
export arch_flags="-arch x86_64"
../configure CFLAGS="$arch_flags" CXXFLAGS="$arch_flags" CPPFLAGS="$arch_flags" LDFLAGS="$arch_flags" OBJCFLAGS="$arch_flags" OBJCXXFLAGS="$arch_flags" --with-osx_cocoa --with-macosx-version-min=10.12 --with-macosx-sdk=/Applications//Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk --prefix="$(pwd)" --enable-monolithic --enable-static --disable-debug --disable-shared --with-regex=builtin --with-expat=builtin --enable-unicode
```

remove the LDFLAGS += -lgomp and the -fopenmp from the Makefile since the OS X clang do not support it. Some better solution?

```
make distclean
make
```

When finished compiling wxWidgets compile wxHexEditor.

Unpack the wxHexEditor and enter its directory
`make mac WXCONFIG=../../wxWidgets-3.0.3/release/wx-config OPTFLAGS="-arch x86_64`

I hope this helps.

**Comment by jerryjeremiah** [comment]
I really appreciate all the help you guys have given to get v0x24 on OSX 10.8.

I am trying to recover a 3.5 TB Truecrypt volume on an OSX volume and I really need to be able to save a 3.5 TB range of bytes using Block Start and Block End - so I hopefully won't have to wait too long for v0.24.  

I would be really happy to help fix bugs for OSX But I can't get it to compile...

I wish I could upgrade the version of OSX I am using but the install stalls during the first reboot and never finishes (I have tried it multiple times)  And I can't build it with the XCode that comes with 10.8 because clang just crashes.  

So if I can't get it to compile I will wait for v0x24 to be released.

Thanks again for all the help,

Jerry

**Comment by EUA** [comment]
You can also install wxwidgets with brew. But you must install brew first.
Than:
`brew install wxwidgets`
`brew install gettext`
`brew link gettext`
after you can compile with
`make mac`

Unfortunately, still have freezing issue with OSX, bug #83

**Comment by RuneN007** [comment]
Whenever you Destroy a Dialog, you should set it to NULL after. This would probably fix you freezes. Example: 

```c++
void HexEditor::GotoDialog( void ) {
    uint64_t newoffset;
    ::GotoDialog *mygoto = new ::GotoDialog( this, newoffset, CursorOffset(), FileLength(), FDtoBlockSize( GetFD() ) );
    if( mygoto->ShowModal() == wxID_OK ) {
        Goto( newoffset );
     }
     mygoto->Destroy();
     mygoto = NULL; // Make sure this variable is not used or tried to be deleted again!!
}

**Comment by EUA** [comment]
@RuneN007 mygoto is **local** variable here. Not used anymore, right? This issue mainly appears just opening "Checksum Dialog" and close after without doing anything. Somehow, dialog kills it self before function kills it but can't figure why. It is probably wxWidgets issue. Not appearing in M$ and Linux ports.

**Comment by RuneN007** [comment]
Try it, and see 😀 Does not freeze here. I know your code works in Linux and M$

Kind Regards

Rune Nordvik

15. des. 2017 kl. 12:15 skrev Erdem U. Altinyurt <notifications@github.com<mailto:notifications@github.com>>:


@RuneN007<https://github.com/runen007> mygoto is local variable here. Not used anymore, right? This issue mainly appears just opening "Checksum Dialog" and close after without doing anything. Somehow, dialog kills it self before function kills it but can't figure why. It is probably wxWidgets issue. Not appearing in M$ and Linux ports.

**Comment by RuneN007** [comment]
It is not your program that causes this. It must be some memory management handled by the GUI libraries that wxWidgets use on MacOS.

Most libraries check if a variable is NULL before it tries to release memory.

It is always considered best practice to set a deleted variable to NULL, Even if it is local.

Kind Regards

Rune Nordvik

15. des. 2017 kl. 12:15 skrev Erdem U. Altinyurt <notifications@github.com<mailto:notifications@github.com>>:


@RuneN007<https://github.com/runen007> mygoto is local variable here. Not used anymore, right? This issue mainly appears just opening "Checksum Dialog" and close after without doing anything. Somehow, dialog kills it self before function kills it but can't figure why. It is probably wxWidgets issue. Not appearing in M$ and Linux ports.

**Comment by EUA** [comment]
It freeze here even nulling the pointer. :/
Continue at issue at #83 if you like to solve.

**Comment by RuneN007** [comment]
Hi again,


You did this on all all dialogs that were using local variables after the destroy, not only the example?. Also make sure that any other variables that you have deleted is set to NULL after deletion.


Maybe I should checkout your code and try too fix it... However, I will not have the Bounty!


Kind Regards


Rune Nordvik

________________________________
Fra: Erdem U. Altinyurt <notifications@github.com>
Sendt: 16. desember 2017 11:11
Til: EUA/wxHexEditor
Kopi: RuneN007; Mention
Emne: Re: [EUA/wxHexEditor] build from source doesn't work on OSX 10.8 (#74)


It freeze here even nulling the pointer. :/
Continue at issue at #83<https://github.com/EUA/wxHexEditor/issues/83> if you like to solve.

**Comment by EUA** [comment]
Issue is the Destroy(). Somehow, on MacOSX port of wxWidgets, destroy() is also free the memory. Using EndModal(0) instead of Destroy() fixed the long waited issue. Could give a release at last!
Thanks.

**Comment by EUA** [comment]
@jerryjeremiah I successfully compiled wxHexEditor on 10.13. Probably it's compatible with 10.8.
If you give your email, I can drop executable for you.
Also updated COMPILE file for easy compilation at OSX.

**Comment by jerryjeremiah** [comment]
Thank you so much!  I am really happy that you were able to solve that issue.  I wish I had been more helpful.  I really appreciate all the hard work.
Jerryjerry_jeremiah@yahoo.com

 
 
  On Sun, 17 Dec 2017 at 3:19 PM, Erdem U. Altinyurt<notifications@github.com> wrote:   
@jerryjeremiah I successfully compiled wxHexEditor on 10.13. Probably it's compatible with 10.8.
If you give your email, I can drop executable for you.
Also updated COMPILE file for easy compilation at OSX.

**Comment by EUA** [comment]
Oops! I miss your message @jerryjeremiah 
Anyway, I released new 0.24 version.
You can download latest version from sourceforge mirrors.
Unfortunately, It's only for 64Bit CPUs because wxWidgets library has some difficulties with i386 compilation on my computer. If you have 32Bit CPU, I could try further to compile for 32Bit version.

Thanks.

**Comment by jerryjeremiah** [comment]
I have the same issue compiling v0.24 with the Xcode that comes with 10.8.5.  I may have to try building a newer version of clang or g++ but that sounds like a lot of work...

**Comment by jerryjeremiah** [comment]
Ok, I have compiled v0.24 with MacOS 10.8.5 but it required some steps.

1. You cannot use wxWidgets 3.0.x - it compiles fine but because the compiler crashes while building wxHexEditor (see my original question)
2. You cannot use wxWidgets 2.8.x because it doesn't compile (it complains it can't find QDGetPictureBounds - I have no idea where it expects to get it from because it isn't there...)
3. wxWidgets 2.9.5 does work but you cannot use `--enable-monolithic` because then wxWidgets compiles libwx_osx_cocoau-2.9.a but wxWidgets expects libwx_osx_cocoaui-2.9.a to exist among others
4. wxWidgets doesn't compile without errors with this version of compiler and wxWidgets 2.9.5 - it has lots of warnings and two errors:

 src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:560:45: error: use of overloaded operator '[]' is ambiguous (with operand types
      'const wxScopedCharBuffer' (aka 'const wxScopedCharTypeBuffer<char>') and 'int')
                                        chr = RenderedHexByte.ToAscii()[0];
 /Users/test/Downloads/wxWidgets-2.9.5/include/wx/buffer.h:159:14: note: candidate function
    CharType operator[](size_t n) const { return data()[n]; }
 src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:560:45: note: built-in candidate operator[](const char *, int)
 src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:560:45: note: built-in candidate operator[](const volatile char *, int)
 src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:572:45: error: use of overloaded operator '[]' is ambiguous (with operand types
      'const wxScopedCharBuffer' (aka 'const wxScopedCharTypeBuffer<char>') and 'int')
                                        chr = RenderedHexByte.ToAscii()[1];
 /Users/test/Downloads/wxWidgets-2.9.5/include/wx/buffer.h:159:14: note: candidate function
    CharType operator[](size_t n) const { return data()[n]; }
 src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:572:45: note: built-in candidate operator[](const char *, int)
 src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:572:45: note: built-in candidate operator[](const volatile char *, int)

5. Because of the errors you have to edit wxHexCtrl.cpp and change `chr = RenderedHexByte.ToAscii()[0];` to `chr = RenderedHexByte.ToAscii()[0l];` and change `chr = RenderedHexByte.ToAscii()[1];` to `chr = RenderedHexByte.ToAscii()[1l];`
6. wxWidgets doesn't link because it can't find libgomp.a so you have to edit the Makefile and change `LDFLAGS += -lgomp` to `LDFLAGS += -L/usr/llvm-gcc-4.2/lib/gcc/i686-apple-darwin11/4.2.1 -lgomp`

So in the end I used the following command lines to compile it:

 cd wxWidgets-2.9.5
 mkdir release
 cd release
 ../configure CFLAGS="$arch_flags" CXXFLAGS="$arch_flags" CPPFLAGS="$arch_flags" LDFLAGS="$arch_flags" OBJCFLAGS="$arch_flags" OBJCXXFLAGS="$arch_flags" --with-macosx-version-min=10.8 --with-macosx-sdk=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/ --enable-static --disable-debug --disable-shared --with-regex=builtin --with-expat=builtin --enable-unicode
 make
 cd ../../wxHexEditor-0.24
 vi Makefile # edit lines as described above
 vi src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp # edit lines as described above
 make mac WXCONFIG=../wxWidgets-2.9.5/release/wx-config OPTFLAGS="-arch i386"

**Comment by jerryjeremiah** [comment]
It does compile and run, but it still isn't right - the window is usable but the menu at the top is for whatever app was active before the program was started. Without a menu you can't do everything you need...
